#############################################################################
# Makefile for building: bin/osg-3d-vis
# Generated by qmake (3.1) (Qt 5.12.12)
# Project:  osg-3d-vis.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile osg-3d-vis.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_PLUGIN -DQT_CHARTS_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -D_REENTRANT -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1z -D_REENTRANT -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../SDK/osg3.4/include -isystem /usr/include/aarch64-linux-gnu/qt5 -isystem /usr/include/aarch64-linux-gnu/qt5/QtCharts -isystem /usr/include/aarch64-linux-gnu/qt5/QtWidgets -isystem /usr/include/aarch64-linux-gnu/qt5/QtGui -isystem /usr/include/aarch64-linux-gnu/qt5/QtCore -I. -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = osg-3d-vis1.0.0
DISTDIR = /data/osg-3d-vis/.tmp/osg-3d-vis1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -L/data/SDK/osg3.4/lib -losg -losgViewer -losgDB -losgGA -losgText -lOpenThreads -losgUtil -losgParticle /usr/lib/aarch64-linux-gnu/libQt5Charts.so /usr/lib/aarch64-linux-gnu/libQt5Widgets.so /usr/lib/aarch64-linux-gnu/libQt5Gui.so /usr/lib/aarch64-linux-gnu/libQt5Core.so /usr/lib/aarch64-linux-gnu/libGL.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/globals.cpp \
		src/main.cpp \
		src/main_window.cpp \
		src/charts/Axis.cpp \
		src/charts/chart.cpp \
		src/charts/ColumnChart.cpp \
		src/charts/CurveChart.cpp \
		src/charts/DotChart.cpp \
		src/charts/ParallelChart.cpp \
		src/charts/PieChart.cpp \
		src/charts/PolylineChart.cpp \
		src/charts/RadarChart.cpp \
		src/earth/Cloud.cpp \
		src/earth/Grass.cpp \
		src/earth/Tree.cpp \
		src/particles/Particle.cpp \
		src/radar/APMRadarRender.cpp \
		src/radar/Concave.cpp \
		src/radar/ConcaveBase.cpp \
		src/radar/Radar.cpp \
		src/radar/radarui.cpp \
		src/velocity_field/rttcamera.cpp \
		src/velocity_field/StreamlineCPU.cpp \
		src/velocity_field/StreamLineCPUMultiPassCreation.cpp \
		src/velocity_field/StreamlineGPU.cpp \
		src/velocity_field/StreamLineSeedPointCalculation.cpp moc_main_window.cpp \
		moc_chart.cpp \
		moc_radarui.cpp \
		moc_streamline_cpu.cpp \
		moc_StreamLineMainWindow.cpp
OBJECTS       = globals.o \
		main.o \
		main_window.o \
		Axis.o \
		chart.o \
		ColumnChart.o \
		CurveChart.o \
		DotChart.o \
		ParallelChart.o \
		PieChart.o \
		PolylineChart.o \
		RadarChart.o \
		Cloud.o \
		Grass.o \
		Tree.o \
		Particle.o \
		APMRadarRender.o \
		Concave.o \
		ConcaveBase.o \
		Radar.o \
		radarui.o \
		rttcamera.o \
		StreamlineCPU.o \
		StreamLineCPUMultiPassCreation.o \
		StreamlineGPU.o \
		StreamLineSeedPointCalculation.o \
		moc_main_window.o \
		moc_chart.o \
		moc_radarui.o \
		moc_streamline_cpu.o \
		moc_StreamLineMainWindow.o
DIST          = /usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/lex.prf \
		osg-3d-vis.pro src/globals.h \
		src/main_window.h \
		src/ui_main_window.h \
		src/util.h \
		src/volumeRender.h \
		src/charts/Axis.h \
		src/charts/chart.h \
		src/charts/ColumnChart.h \
		src/charts/CurveChart.h \
		src/charts/DotChart.h \
		src/charts/ParallelChart.h \
		src/charts/PieChart.h \
		src/charts/PolylineChart.h \
		src/charts/RadarChart.h \
		src/charts/ui_chart.h \
		src/earth/Cloud.h \
		src/earth/Grass.h \
		src/earth/Tree.h \
		src/loader/OSGB.h \
		src/particles/Particle.h \
		src/radar/APMRadarRender.h \
		src/radar/Concave.h \
		src/radar/ConcaveBase.h \
		src/radar/Radar.h \
		src/radar/radarui.h \
		src/radar/ui_radar.h \
		src/velocity_field/rttcamera.h \
		src/velocity_field/streamline_cpu.h \
		src/velocity_field/StreamlineCPU.h \
		src/velocity_field/StreamlineGPU.h \
		src/velocity_field/StreamLineMainWindow.h \
		src/velocity_field/ui_streamline.h \
		src/velocity_field/ui_streamline_cpu.h \
		src/velocity_field/VelocityLIC.h \
		src/velocity_field/VolumeLIC.h \
		src/velocity_field/VortexDetect.h \
		src/earth/Earth.hpp \
		src/pbr/pbr.hpp src/globals.cpp \
		src/main.cpp \
		src/main_window.cpp \
		src/charts/Axis.cpp \
		src/charts/chart.cpp \
		src/charts/ColumnChart.cpp \
		src/charts/CurveChart.cpp \
		src/charts/DotChart.cpp \
		src/charts/ParallelChart.cpp \
		src/charts/PieChart.cpp \
		src/charts/PolylineChart.cpp \
		src/charts/RadarChart.cpp \
		src/earth/Cloud.cpp \
		src/earth/Grass.cpp \
		src/earth/Tree.cpp \
		src/particles/Particle.cpp \
		src/radar/APMRadarRender.cpp \
		src/radar/Concave.cpp \
		src/radar/ConcaveBase.cpp \
		src/radar/Radar.cpp \
		src/radar/radarui.cpp \
		src/velocity_field/rttcamera.cpp \
		src/velocity_field/StreamlineCPU.cpp \
		src/velocity_field/StreamLineCPUMultiPassCreation.cpp \
		src/velocity_field/StreamlineGPU.cpp \
		src/velocity_field/StreamLineSeedPointCalculation.cpp
QMAKE_TARGET  = osg-3d-vis
DESTDIR       = bin/
TARGET        = bin/osg-3d-vis
TARGETD       = bin/osg-3d-vis


first: all
####### Build rules

bin/osg-3d-vis:  $(OBJECTS)  
	@test -d bin/ || mkdir -p bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: osg-3d-vis.pro /usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/lex.prf \
		osg-3d-vis.pro
	$(QMAKE) -o Makefile osg-3d-vis.pro
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/lex.prf:
osg-3d-vis.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile osg-3d-vis.pro

qmake_all: FORCE


all: Makefile bin/osg-3d-vis

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/globals.h src/main_window.h src/ui_main_window.h src/util.h src/volumeRender.h src/charts/Axis.h src/charts/chart.h src/charts/ColumnChart.h src/charts/CurveChart.h src/charts/DotChart.h src/charts/ParallelChart.h src/charts/PieChart.h src/charts/PolylineChart.h src/charts/RadarChart.h src/charts/ui_chart.h src/earth/Cloud.h src/earth/Grass.h src/earth/Tree.h src/loader/OSGB.h src/particles/Particle.h src/radar/APMRadarRender.h src/radar/Concave.h src/radar/ConcaveBase.h src/radar/Radar.h src/radar/radarui.h src/radar/ui_radar.h src/velocity_field/rttcamera.h src/velocity_field/streamline_cpu.h src/velocity_field/StreamlineCPU.h src/velocity_field/StreamlineGPU.h src/velocity_field/StreamLineMainWindow.h src/velocity_field/ui_streamline.h src/velocity_field/ui_streamline_cpu.h src/velocity_field/VelocityLIC.h src/velocity_field/VolumeLIC.h src/velocity_field/VortexDetect.h src/earth/Earth.hpp src/pbr/pbr.hpp $(DISTDIR)/
	$(COPY_FILE) --parents src/globals.cpp src/main.cpp src/main_window.cpp src/charts/Axis.cpp src/charts/chart.cpp src/charts/ColumnChart.cpp src/charts/CurveChart.cpp src/charts/DotChart.cpp src/charts/ParallelChart.cpp src/charts/PieChart.cpp src/charts/PolylineChart.cpp src/charts/RadarChart.cpp src/earth/Cloud.cpp src/earth/Grass.cpp src/earth/Tree.cpp src/particles/Particle.cpp src/radar/APMRadarRender.cpp src/radar/Concave.cpp src/radar/ConcaveBase.cpp src/radar/Radar.cpp src/radar/radarui.cpp src/velocity_field/rttcamera.cpp src/velocity_field/StreamlineCPU.cpp src/velocity_field/StreamLineCPUMultiPassCreation.cpp src/velocity_field/StreamlineGPU.cpp src/velocity_field/StreamLineSeedPointCalculation.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) bin/$(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++1z -dM -E -o moc_predefs.h /usr/lib/aarch64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_main_window.cpp moc_chart.cpp moc_radarui.cpp moc_streamline_cpu.cpp moc_StreamLineMainWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_main_window.cpp moc_chart.cpp moc_radarui.cpp moc_streamline_cpu.cpp moc_StreamLineMainWindow.cpp
moc_main_window.cpp: src/main_window.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /data/osg-3d-vis/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/data/osg-3d-vis -I/data/SDK/osg3.4/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtCharts -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/aarch64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/aarch64-linux-gnu/9/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include src/main_window.h -o moc_main_window.cpp

moc_chart.cpp: src/charts/chart.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /data/osg-3d-vis/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/data/osg-3d-vis -I/data/SDK/osg3.4/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtCharts -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/aarch64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/aarch64-linux-gnu/9/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include src/charts/chart.h -o moc_chart.cpp

moc_radarui.cpp: src/radar/radarui.h \
		src/radar/Radar.h \
		src/util.h \
		src/radar/APMRadarRender.h \
		src/radar/Concave.h \
		src/radar/ConcaveBase.h \
		src/volumeRender.h \
		src/radar/ui_radar.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /data/osg-3d-vis/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/data/osg-3d-vis -I/data/SDK/osg3.4/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtCharts -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/aarch64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/aarch64-linux-gnu/9/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include src/radar/radarui.h -o moc_radarui.cpp

moc_streamline_cpu.cpp: src/velocity_field/streamline_cpu.h \
		src/velocity_field/ui_streamline_cpu.h \
		src/velocity_field/StreamlineCPU.h \
		src/util.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /data/osg-3d-vis/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/data/osg-3d-vis -I/data/SDK/osg3.4/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtCharts -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/aarch64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/aarch64-linux-gnu/9/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include src/velocity_field/streamline_cpu.h -o moc_streamline_cpu.cpp

moc_StreamLineMainWindow.cpp: src/velocity_field/StreamLineMainWindow.h \
		src/velocity_field/ui_streamline.h \
		src/velocity_field/StreamlineGPU.h \
		src/util.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /data/osg-3d-vis/moc_predefs.h -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -I/data/osg-3d-vis -I/data/SDK/osg3.4/include -I/usr/include/aarch64-linux-gnu/qt5 -I/usr/include/aarch64-linux-gnu/qt5/QtCharts -I/usr/include/aarch64-linux-gnu/qt5/QtWidgets -I/usr/include/aarch64-linux-gnu/qt5/QtGui -I/usr/include/aarch64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/aarch64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/aarch64-linux-gnu/9/include -I/usr/local/include -I/usr/include/aarch64-linux-gnu -I/usr/include src/velocity_field/StreamLineMainWindow.h -o moc_StreamLineMainWindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

globals.o: src/globals.cpp src/globals.h \
		src/util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o globals.o src/globals.cpp

main.o: src/main.cpp src/earth/Earth.hpp \
		src/globals.h \
		src/util.h \
		src/particles/Particle.h \
		src/charts/chart.h \
		src/charts/ColumnChart.h \
		src/charts/DotChart.h \
		src/earth/Cloud.h \
		src/earth/Grass.h \
		src/earth/Tree.h \
		src/loader/OSGB.h \
		src/radar/Radar.h \
		src/radar/APMRadarRender.h \
		src/radar/Concave.h \
		src/radar/ConcaveBase.h \
		src/volumeRender.h \
		src/velocity_field/StreamlineCPU.h \
		src/velocity_field/StreamlineGPU.h \
		src/velocity_field/VelocityLIC.h \
		src/radar/radarui.h \
		src/radar/ui_radar.h \
		src/pbr/pbr.hpp \
		src/velocity_field/rttcamera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

main_window.o: src/main_window.cpp src/main_window.h \
		src/ui_main_window.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main_window.o src/main_window.cpp

Axis.o: src/charts/Axis.cpp src/charts/Axis.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Axis.o src/charts/Axis.cpp

chart.o: src/charts/chart.cpp src/charts/chart.h \
		src/charts/ui_chart.h \
		src/charts/Axis.h \
		src/charts/ColumnChart.h \
		src/charts/DotChart.h \
		src/charts/PolylineChart.h \
		src/charts/CurveChart.h \
		src/charts/PieChart.h \
		src/charts/ParallelChart.h \
		src/charts/RadarChart.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o chart.o src/charts/chart.cpp

ColumnChart.o: src/charts/ColumnChart.cpp src/charts/ColumnChart.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ColumnChart.o src/charts/ColumnChart.cpp

CurveChart.o: src/charts/CurveChart.cpp src/charts/CurveChart.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CurveChart.o src/charts/CurveChart.cpp

DotChart.o: src/charts/DotChart.cpp src/charts/DotChart.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DotChart.o src/charts/DotChart.cpp

ParallelChart.o: src/charts/ParallelChart.cpp src/charts/ParallelChart.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ParallelChart.o src/charts/ParallelChart.cpp

PieChart.o: src/charts/PieChart.cpp src/charts/PieChart.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PieChart.o src/charts/PieChart.cpp

PolylineChart.o: src/charts/PolylineChart.cpp src/charts/PolylineChart.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PolylineChart.o src/charts/PolylineChart.cpp

RadarChart.o: src/charts/RadarChart.cpp src/charts/RadarChart.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RadarChart.o src/charts/RadarChart.cpp

Cloud.o: src/earth/Cloud.cpp src/earth/Cloud.h \
		src/util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Cloud.o src/earth/Cloud.cpp

Grass.o: src/earth/Grass.cpp src/earth/Grass.h \
		src/util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Grass.o src/earth/Grass.cpp

Tree.o: src/earth/Tree.cpp src/earth/Tree.h \
		src/util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Tree.o src/earth/Tree.cpp

Particle.o: src/particles/Particle.cpp src/particles/Particle.h \
		src/globals.h \
		src/util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Particle.o src/particles/Particle.cpp

APMRadarRender.o: src/radar/APMRadarRender.cpp src/radar/APMRadarRender.h \
		src/radar/Concave.h \
		src/radar/ConcaveBase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o APMRadarRender.o src/radar/APMRadarRender.cpp

Concave.o: src/radar/Concave.cpp src/radar/Concave.h \
		src/radar/ConcaveBase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Concave.o src/radar/Concave.cpp

ConcaveBase.o: src/radar/ConcaveBase.cpp src/radar/ConcaveBase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ConcaveBase.o src/radar/ConcaveBase.cpp

Radar.o: src/radar/Radar.cpp src/radar/Radar.h \
		src/util.h \
		src/radar/APMRadarRender.h \
		src/radar/Concave.h \
		src/radar/ConcaveBase.h \
		src/volumeRender.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Radar.o src/radar/Radar.cpp

radarui.o: src/radar/radarui.cpp src/radar/radarui.h \
		src/radar/Radar.h \
		src/util.h \
		src/radar/APMRadarRender.h \
		src/radar/Concave.h \
		src/radar/ConcaveBase.h \
		src/volumeRender.h \
		src/radar/ui_radar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o radarui.o src/radar/radarui.cpp

rttcamera.o: src/velocity_field/rttcamera.cpp src/velocity_field/rttcamera.h \
		src/util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rttcamera.o src/velocity_field/rttcamera.cpp

StreamlineCPU.o: src/velocity_field/StreamlineCPU.cpp src/velocity_field/StreamlineCPU.h \
		src/util.h \
		src/velocity_field/streamline_cpu.h \
		src/velocity_field/ui_streamline_cpu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StreamlineCPU.o src/velocity_field/StreamlineCPU.cpp

StreamLineCPUMultiPassCreation.o: src/velocity_field/StreamLineCPUMultiPassCreation.cpp src/velocity_field/StreamlineCPU.h \
		src/util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StreamLineCPUMultiPassCreation.o src/velocity_field/StreamLineCPUMultiPassCreation.cpp

StreamlineGPU.o: src/velocity_field/StreamlineGPU.cpp src/velocity_field/StreamlineGPU.h \
		src/util.h \
		src/velocity_field/StreamLineMainWindow.h \
		src/velocity_field/ui_streamline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StreamlineGPU.o src/velocity_field/StreamlineGPU.cpp

StreamLineSeedPointCalculation.o: src/velocity_field/StreamLineSeedPointCalculation.cpp src/velocity_field/StreamlineCPU.h \
		src/util.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StreamLineSeedPointCalculation.o src/velocity_field/StreamLineSeedPointCalculation.cpp

moc_main_window.o: moc_main_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_main_window.o moc_main_window.cpp

moc_chart.o: moc_chart.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_chart.o moc_chart.cpp

moc_radarui.o: moc_radarui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_radarui.o moc_radarui.cpp

moc_streamline_cpu.o: moc_streamline_cpu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_streamline_cpu.o moc_streamline_cpu.cpp

moc_StreamLineMainWindow.o: moc_StreamLineMainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_StreamLineMainWindow.o moc_StreamLineMainWindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

